#!/bin/sh

brew install neovim lazygit fd ripgrep tldr bat fzf tokei highlight jq \
  rlwrap stow zoxide lf vivid \
  rubymine puma/puma/puma-dev \
  gh awscli \
  mcfly just \
  zsh-syntax-highlighting zsh-autosuggestions zsh-history-substring-search \
  romkatv/powerlevel10k/powerlevel10k \
  coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep \
  gnupg gcc moreutils xh difftastic git-delta pandoc watch shellcheck \
  mise go \
  temurin@21

brew install --cask visual-studio-code rectangle \
  homebrew/cask/font-meslo-lg-nerd-font \
  font-iosevka-nerd-font iterm2 unnaturalscrollwheels ccmenu shottr keepassxc \
  slack microsoft-teams docker zoom ccmenu

echo "Remember to use:"
echo "\tgit config --global user.name 'Christopher Chang'"
echo "\tgit config --global user.email <email>"

echo "Remember to use (delta):"
echo "\tgit config --global core.pager delta"
echo "\tgit config --global interactive.diffFilter 'delta --color-only'"
echo "\tgit config --global delta.navigate true"
echo "\tgit config --global merge.conflictStyle zdiff3"
