#!/bin/sh

brew install neovim lazygit fd ripgrep tldr bat fzf tokei highlight jq \
  rlwrap stow zoxide lf vivid \
  rubymine \
  gh awscli \
  mcfly just \
  zsh-syntax-highlighting zsh-autosuggestions zsh-history-substring-search \
  romkatv/powerlevel10k/powerlevel10k \
  coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep \
  gcc moreutils xh difftastic git-delta pandoc watch shellcheck \
  temurin@21

brew install --cask visual-studio-code rectangle \
  homebrew/cask/font-meslo-lg-nerd-font \
  font-iosevka-nerd-font iterm2 unnaturalscrollwheels
