#!/usr/bin/bash
DOTFILES=$(pwd)

cd ~
ln -sf $DOTFILES/.tmux.conf
ln -sf $DOTFILES/.vimrc
ln -sf $DOTFILES/.zshrc
ln -sf $DOTFILES/.zshenv
ln -sf $DOTFILES/.bashrc
ln -sf $DOTFILES/.profile
ln -sf $DOTFILES/.Xresources

echo "Symlinking openbox config files..."
if ! [ -d "$DIRECTORY" ]; then
	mkdir -p ~/.config/openbox/
fi
cd ~/.config/openbox/
ln -sf $DOTFILES/.config/openbox/autostart
ln -sf $DOTFILES/.config/openbox/menu.xml
ln -sf $DOTFILES/.config/openbox/rc.xml

printf "Do you want to symlink .emacs.d? [yn] "
read symlink

if [ $symlink = "y" ]; then
	cd ~
	
	echo "Symlinking .emacs.d..."

	ln -s $DOTFILES/.emacs.d

	echo "Done!"
elif [ $symlink = "n" ]; then
	echo "Ok. Not symlinking .emacs.d..."
else
	echo "That was not a valid choice. Not symlinking, just in case."
fi
