#!/usr/bin/bash
DOTFILES=$(pwd)

ln -sft ~ $DOTFILES/.tmux.conf $DOTFILES/.vimrc $DOTFILES/.zshrc $DOTFILES/.zshrnv \
   $DOTFILES/.bashrc $DOTFILES/.profile $DOTFILES/.Xresources
mkdir -p ~/.ncmpcpp/
ln -sft ~/.ncmpcpp/ $DOTFILES/.ncmpcpp/*
mkdir -p ~/.config/mpd
ln -sft ~/.config/mpd/ $DOTFILES/.config/mpd/mpd.conf

cd ~

echo "Symlinking openbox config files..."
mkdir -p ~/.config/openbox/
ln -sft ~/.config/openbox $DOTFILES/.config/openbox/autostart $DOTFILES/.config/openbox/menu.xml $DOTFILES/.config/openbox/rc.xml

printf "Do you want to symlink .emacs.d? [yn] "
read symlink

if [ $symlink = "y" ]; then
	cd ~
	
	echo "Symlinking .emacs.d..."

	ln -s $DOTFILES/.emacs.d

	echo "Done!"
elif [ $symlink = "n" ]; then
	echo "Ok. Not symlinking .emacs.d..."
else
	echo "That was not a valid choice. Not symlinking, just in case."
fi
