#!/usr/bin/env sh

autorandr -c

case "$HOSTNAME" in
  # "alien")
  #   ~/dotfiles/multi/monitor_setup.d/alien
  #   ;;
	"msi")
		# ~/dotfiles/multi/monitor_setup.d/msi
		# xrandr --output eDP-1-1 --primary
		SCREEN=$(xrandr | grep -e eDP -e ' connected' | awk '{print $1}')
		xrandr --output ${SCREEN} --primary
		;;
esac
