#!/usr/bin/env sh

if [ "$HOSTNAME" = "msi" ]; then
  # Set the touchpad senstivity
  # xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.6
  # xinput set-prop 14 'libinput Accel Speed' 0.6
	TOUCHPAD_ID=$(xinput --list | grep TouchPad | awk '{print $6}' | cut -c 4-)

  	xinput set-prop "$TOUCHPAD_ID" 'libinput Accel Speed' 0.6

	# Enable tap-to-click
	xinput set-prop "$TOUCHPAD_ID" 'libinput Tapping Enabled' 1

  # Disable tapping drag on touchpad
  xinput set-prop "$TOUCHPAD_ID" 'libinput Tapping Drag Enabled' 0

	# Use two-finger click for "right click" and three-finger click for "middle click"
	xinput set-prop "$TOUCHPAD_ID" 'libinput Click Method Enabled' {0,1}
fi
