#!/usr/bin/env sh

if [ "$HOSTNAME" = "msi" ]; then
  # Set the touchpad senstivity
  xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.6
  # Disable tapping drag on touchpad
  xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Drag Enabled' 0
fi
