#!/usr/bin/env sh

dropbox &
if ! ps -e | grep syncthing-gtk; then
	syncthing-gtk --minimized &
fi

if [ "$HOSTNAME" = "msi" ]; then
	if ! ps -e | grep Discord; then
		discord --start-minimized &
	fi
fi
