#!/bin/bash

set -euo pipefail

ARTICLES="$HOME/projects/blog/articles"

if [ "$#" -ne 1 ]; then
  ME=$(basename "$0")
  echo "Usage: ${ME} file-title"
  exit 1
fi

FILE_TITLE="${1}"

DATE=$(date +'%Y-%m-%d')
FILE="$ARTICLES/${DATE}-${FILE_TITLE}.md"
echo "${FILE}"
${VISUAL} "${FILE}"
