#!/usr/bin/env python3

# Force full composition pipeline for atttached monitor

import subprocess
import sys
import re

nvoutput = subprocess.run(["nvidia-settings", "--query", "CurrentMetaMode"], \
    capture_output=True, text=True)

# Obtain settings and put them into a list
out = nvoutput.stdout.strip()
print(out)

pattern = re.compile("(.* :: )(?P<name>.+)(: )(?P<mode>[^\s]+x[^\s]+)(.*) \{(?P<settings>.*)\}")
top_parts = pattern.match(out)

settings = top_parts['settings'].split(', ')

if "ForceFullCompositionPipeline=On" in settings and \
   "ForceCompositionPipeline=On" in settings:
    sys.exit("Already full composition!")

if not "ForceFullCompositionPipeline=On" in settings:
    settings.append("ForceFullCompositionPipeline=On")
if not "ForceCompositionPipeline=On" in settings:
    settings.append("ForceCompositionPipeline=On")

settings.append("ForceCompositionPipeline=On")
print("Settings:")
print(settings)
print("\n")

# Reattach settings back into meta mode string
meta_mode = f"{top_parts['name']}: {top_parts['mode']} {{{', '.join(settings)}}}"
subprocess.run(["nvidia-settings", "--assign", "CurrentMetaMode=" + meta_mode])
