#!/bin/sh

INPUT_FILE="$1"
FILENAME_WITHOUT_EXTENSION="${INPUT_FILE%.*}"
OUTPUT_FILE="$FILENAME_WITHOUT_EXTENSION.ogg"

ffmpeg -i "$INPUT_FILE" -c:a copy -c:v copy -disposition:v:0 attached_pic "$OUTPUT_FILE"
