#!/usr/bin/env python

import socket
import os
import sys
import json


def change_focus(direction: str) -> None:
    active_window_info = json.loads(request_ipc("j/activewindow"))
    address: str = active_window_info["address"]
    grouped: list[str] = active_window_info["grouped"]
    if len(grouped) > 0:
        loc = grouped.index(address)
        if direction == "r" and loc == len(grouped) - 1:
            request_ipc(f"dispatch movefocus {direction}")
        elif direction == "l" and loc == 0:
            request_ipc(f"dispatch movefocus {direction}")
        elif direction == "r":
            request_ipc("dispatch changegroupactive f")
        elif direction == "l":
            request_ipc("dispatch changegroupactive b")
    else:
        request_ipc(f"dispatch movefocus {direction}")


def change_window_place(direction: str) -> None:
    active_window_info = json.loads(request_ipc("j/activewindow"))
    address: str = active_window_info["address"]
    grouped: list[str] = active_window_info["grouped"]
    if len(grouped) > 0:
        loc = grouped.index(address)
        if direction == "r" and loc == len(grouped) - 1:
            request_ipc(f"dispatch movewindoworgroup {direction}")
        elif direction == "l" and loc == 0:
            request_ipc(f"dispatch movewindoworgroup {direction}")
        elif direction == "r":
            request_ipc("dispatch movegroupwindow f")
        elif direction == "l":
            request_ipc("dispatch movegroupwindow b")
    else:
        request_ipc(f"dispatch movewindoworgroup {direction}")


def request_ipc(arg: str) -> str:
    request_socket = connect_to_hyprland_socket(".socket.sock")

    try:
        # request_socket.send(bytes(f"/dispatch movefocus {direction}", encoding="utf-8"))
        request_socket.send(bytes(arg, encoding="utf-8"))
        data = request_socket.recv(8192).decode("utf-8")
        if not data:
            raise Exception("Connection closed by Hyprland")
    finally:
        request_socket.close()

    return data


def process_event_line(line: str) -> None:
    parts = line.split(">>")
    if parts[0] == "custom":
        match parts[1]:
            case "changefocus":
                change_focus(parts[2])
            case "changewindowplace":
                change_window_place(parts[2])


def connect_to_hyprland_socket(name: str) -> socket.socket:
    # Get necessary environment variables
    # Fallback to default paths if variables are not set (adjust if needed)
    runtime_dir = os.environ.get("XDG_RUNTIME_DIR", "/tmp")
    instance_signature = os.environ.get("HYPRLAND_INSTANCE_SIGNATURE")

    if not instance_signature:
        print("Error: HYPRLAND_INSTANCE_SIGNATURE not found in environment variables.")
        sys.exit(1)

    socket_path = f"{runtime_dir}/hypr/{instance_signature}/{name}"

    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(socket_path)

    return s


if __name__ == "__main__":
    print("Connecting to .socket2.sock socket")
    event_socket = connect_to_hyprland_socket(".socket2.sock")

    while True:
        # Read data line by line
        data = event_socket.recv(1024).decode("utf-8")
        if not data:
            print("Connection closed by Hyprland.")
            break
        # Hyprland sends events line by line
        for line in data.strip().split("\n"):
            if line:
                process_event_line(line)
