#!/bin/sh

# Modified from https://bbs.archlinux.org/viewtopic.php?id=235555

gawk -F'[][ :-]' '
/upgrade$/ {
  last = mktime($2 " " $3 " " substr($4, 0, 2) " " substr($4, 4) " " $5 " " $6)
}

END {
   s = systime() - last;
   d = int(s / 86400);
   h = int((s - d * 86400) / 3600)
   m = int((s - d * 86400 - h * 3600) / 60)
   printf "Last update was %d days %d hours and %d minutes ago\nRun pacman now!\n", d, h, m
}
' /var/log/pacman.log
