#!/bin/sh

# This symlinks scripts from ~/dotfiles/scripts to ~/bin.

BIN="$HOME/bin"

mkdir -p "$BIN"

if echo "$PATH" | grep -q "$BIN"; then
  echo "PATH correct 👍: contains $BIN"
else
  echo "Warning ⚠️: PATH does not include $BIN"
fi

for FILE in ~/dotfiles/scripts/*; do
  if [ -f "$BIN/$(basename "$FILE")" ]; then
    echo "File exists ✅: $FILE"
  else
    ln -s "$FILE" "$BIN"
    echo "File symlinked 🔗: $FILE"
  fi
done
