#!/usr/bin/env python

import os
import subprocess
import fnmatch

packages = [
    "iwd",
    "networkmanager",
    "networkmanager-qt",
    "plasma-nm",
    "plasma-vault",
    "plasma-welcome",
]

if os.getuid() != 0:
    raise Exception("This program must be run as sudo")

files_to_rm: set[str] = set()

for file in os.listdir("/var/cache/pacman/pkg"):
    for package in packages:
        if fnmatch.fnmatch(file, f"{package}*x86_64.pkg*"):
            files_to_rm.add(file)

for file in files_to_rm:
    path = f"/var/cache/pacman/pkg/{file}"
    print(f"Removing {path}")
    os.remove(path)

subprocess.run(["sudo", "pacman", "-R", *packages])
