#!/bin/sh

yt-dlp \
  -x --audio-format opus \
  -o '%(playlist_autonumber)s %(title)s.%(ext)s' \
  --embed-metadata \
  --embed-thumbnail \
  --no-overwrites \
  --cookies-from-browser=firefox \
  "$@"
