#!/bin/sh

yt-dlp \
  -o "%(release_date,upload_date)s %(release_timestamp,timestamp)s %(channel)s [%(id)s] [%(duration_string)s] %(title)s.%(ext)s" \
  -S "res:1080" \
  --cookies-from-browser=firefox \
  --mark-watched \
  --embed-chapters \
  --no-playlist \
  "$@"
